{{- define "backup.enabled" -}}
{{- .Values.velero.enabled -}}
{{- end -}}
{{ if eq (include "backup.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: backup
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '{{ .Values.velero.enabled }}'
    server: '*'
  sourceRepos:
  - '*'
{{ end }}