{{- define "velero.enabled" -}}
{{- .Values.velero.enabled -}}
{{- end -}}
{{- if eq (include "velero.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.velero.namespace }}
    server: https://kubernetes.default.svc
  project: backup
  source:
    chart: {{ .Values.velero.chart.name }}
    repoURL: {{ .Values.velero.chart.repo }}
    targetRevision: {{ .Values.velero.chart.version }}
    helm:
      version: v3
      values: |-
        {{- if .Values.velero.values.monitor }}
        metrics:
          enabled: true
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8085"
            prometheus.io/path: "/metrics"
        {{- else }}
        metrics:
          enabled: false
        {{- end }}
        credentials:
          secretContents:
            cloud: |-
              {{- tpl .Values.velero.values.cloudSecretContent . | nindent 14 }}
        configuration:
          provider: {{ .Values.velero.values.provider }}
          backupStorageLocation:
            name: {{ .Values.velero.values.backupStorageLocation.name }}
            bucket: {{ .Values.velero.values.backupStorageLocation.bucket }}
            config:
              region: {{ .Values.velero.values.backupStorageLocation.region }}
          volumeSnapshotLocation:
            name: {{ .Values.velero.values.volumeSnapshotLocation.name }}
            config:
              region: {{ .Values.velero.values.volumeSnapshotLocation.region }}
          initContainers:
            - name: velero-plugin-{{ .Values.velero.values.provider }}
              image:velero/velero-plugin-for-{{ .Values.velero.values.provider }}:
              mountPath: /target
              volumeMounts:
                - name: plugins
{{ end }}