{{ if eq (include "logging.namespace" .) "elastic-system" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ (include "logging.namespace" .) }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    chart: {{ .Values.logging.eckCrds.chart.name }}
    repoURL: {{ .Values.logging.eckCrds.chart.repo }}
    targetRevision: {{ .Values.logging.eckCrds.chart.version }}
    helm:
      version: v3
      values: |-
{{ end }}
