{{ if and .Values.logging.eckTpl.enabled (eq (include "logging.namespace" .) "elastic-system") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-tpl
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ (include "logging.namespace" .) }}
    server: https://kubernetes.default.svc
  project: logging
  source:
    path: {{ .Values.logging.eckTpl.chart.path }}
    repoURL: {{ .Values.logging.eckTpl.chart.repo }}
    targetRevision: {{ .Values.logging.eckTpl.chart.targetRevision }}
    helm:
      version: v3
      values: |-
        clusterSpec:
          name: {{ .Values.logging.eckTpl.values.clusterSpec.name }}
          version: {{ .Values.logging.eckTpl.values.clusterSpec.version }}
          elasticsearch:
            count: {{ .Values.logging.eckTpl.values.clusterSpec.elasticsearch.count }}
            config: {{ toYaml .Values.logging.eckTpl.values.clusterSpec.elasticsearch.config | nindent 14 }}
            serviceType: {{ .Values.logging.eckTpl.values.clusterSpec.elasticsearch.serviceType }}
            {{- if .Values.default.storageClass }}
            persistence:
              enabled: true
              storageClass: {{ .Values.default.storageClass }}
              size: {{ quote .Values.logging.eckTpl.values.clusterSpec.elasticsearch.pvcSize }}
              {{- else }}
            persistence:
              enabled: false
            {{- end }}
          kibana:
            count: {{ .Values.logging.eckTpl.values.clusterSpec.kibana.count }}
            {{- if eq .Values.ingress.ingressDefinition.dns.mode "domain" }}
            kibanaPath: "/{{ .Values.logging.eckTpl.values.clusterSpec.kibana.ingress.name }}"
            {{- end }}
            config: {{ toYaml .Values.logging.eckTpl.values.clusterSpec.kibana.config | nindent 14 }}
            {{- if and (eq (include "ingress.namespace" .) "traefik-system") .Values.logging.eckTpl.values.clusterSpec.kibana.ingress.enabled }}
            {{- include "helm-ingress.defaultSpec" (dict "name" .Values.logging.eckTpl.values.clusterSpec.kibana.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.traefik.values.ingressAnnotations) | nindent 12 -}}
            {{- end }}
            {{- if and (eq (include "ingress.namespace" .) "ingress-nginx") .Values.logging.eckTpl.values.clusterSpec.kibana.ingress.enabled }}
              {{- include "helm-ingress.defaultSpec" (dict "name" .Values.logging.eckTpl.values.clusterSpec.kibana.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.nginx.values.ingressAnnotations) | nindent 12 -}}
            {{- end }}
{{ end }}
