{{- define "eck.enabled" -}}
{{- and .Values.logging.enabled (eq (include "logging.namespace" .) "elastic-namespace") -}}
{{- end -}}
{{ if eq (include "eck.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ (include "logging.namespace" .) }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    path: {{ .Values.eck.chart.path }}
    repoURL: {{ .Values.eck.chart.repo }}
    targetRevision: {{ .Values.eck.chart.targetRevision }}
    helm:
      version: v3
      values: |-
{{ end }}
