{{- define "networking.enabled" -}}
{{- or (eq (include "ingress.namespace" .) "traefik-system") (eq (include "ingress.namespace" .) "ingress-nginx") -}}
{{- end -}}
{{ if eq (include "networking.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  {{- if eq (include "ingress.namespace" .) "traefik-system" }}
  - namespace: 'traefik-system'
    server: '*'
  {{- else if eq (include "ingress.namespace" .) "ingress-nginx" }}
  - namespace: 'ingress-nginx'
    server: '*'
  {{- end }}
  {{- if .Values.certmanager.enabled }}
  - namespace: '{{ .Values.certmanager.namespace }}'
    server: '*'
  - namespace: kube-system
    server: '*'
  {{- end }}
  sourceRepos:
  - '*'
{{ end }}