apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.clusterSpec.name }}
  namespace: {{ .Release.Namespace | default "" }}
spec:
  version: {{ .Values.clusterSpec.version }}
  test: {{ include "generateSpecificCerts" . }}
  http:
    service:
      spec:
        type: {{ .Values.clusterSpec.elasticsearch.serviceType }}
  {{- if not .Values.clusterSpec.elasticsearch.tls.enabled }}
    tls:
      selfSignedCertificate:
        disabled: true
  {{- else if eq (include "generateSpecificCerts" .) "true" }}
    tls:
      selfSignedCertificate:
        subjectAltNames:
        {{- range $index, $map := .Values.clusterSpec.elasticsearch.tls.subjectAltNames }}
          {{- range $k, $v := $map }}
          - {{ $k }}: {{ $v }}
          {{- end }}
        {{- end }}
  {{- end }}
  nodeSets:
  - name: default
    count: {{ .Values.clusterSpec.elasticsearch.count }}
    config: {{- toYaml .Values.clusterSpec.elasticsearch.config | nindent 6 }}
    {{- if .Values.clusterSpec.elasticsearch.persistence.enabled }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - {{ .Values.clusterSpec.elasticsearch.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.clusterSpec.elasticsearch.persistence.size }}
        storageClassName: {{ .Values.clusterSpec.elasticsearch.persistence.storageClassName }}
    {{- end }}