{{- if .Values.clusterSpec.filebeat.enabled }}
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Values.clusterSpec.name }}
spec:
  type: filebeat
  version: {{ .Values.clusterSpec.version }}
  elasticsearchRef:
    name: {{ .Values.clusterSpec.name }}
  config: {{- toYaml .Values.clusterSpec.filebeat.config | nindent 4 }}
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
        {{- if .Values.clusterSpec.filebeat.mounts }}
          volumeMounts:
          {{- range .Values.clusterSpec.filebeat.mounts }}
          - name: {{ .name }}
            mountPath: {{ .path }}
            {{- end }}
        {{- end }}
        {{- if .Values.clusterSpec.filebeat.mounts }}
        volumes:
          {{- range .Values.clusterSpec.filebeat.mounts }}
          - name: {{ .name }}
            hostPath:
              path: {{ .path }}
          {{- end }}
        {{- end }}
{{- end }}