{{- if .Values.clusterSpec.kibana.ingress.enabled }}
{{ $clusterName := .Values.clusterSpec.name }}
{{ $kubeGitVersion := .Capabilities.KubeVersion.GitVersion }}
{{- if semverCompare ">=1.14-0" $kubeGitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $clusterName }}-kb
  namespace: {{ .Release.Namespace | default "" }}
  {{- with .Values.clusterSpec.kibana.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.clusterSpec.kibana.ingress.tls }}
  tls:
    {{- range .Values.clusterSpec.kibana.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.clusterSpec.kibana.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.14-0" $kubeGitVersion -}}
            pathType: Prefix
            {{- end }}
            backend:
              serviceName: {{ $clusterName }}-kb-http
              servicePort: 80
    {{- end }}
{{- end }}
