{{- define "starboard.enabled" -}}
{{- .Values.starboard.enabled -}}
{{- end -}}
{{ if eq (include "starboard.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.starboard.namespace }}
    server: https://kubernetes.default.svc
  project: security
  source:
    chart: {{ .Values.starboard.chart.name }}
    repoURL: {{ .Values.starboard.chart.repo }}
    targetRevision: {{ .Values.starboard.chart.version }}
    helm:
      version: v3
      values: |
        targetNamespaces: {{ quote .Values.starboard.values.targetNamespaces }}
        excludeNamespaces: {{ quote .Values.starboard.values.excludeNamespaces }}
        trivy:
          imageRef: {{ .Values.starboard.values.trivy.imageRef }}
          mode: Standalone
          {{- if .Values.proxies.enabled }}
          httpProxy: {{ .Values.proxies.value }}
          httpsProxy: {{ .Values.proxies.value }}
          noProxy: {{ .Values.proxies.noProxy }}
          {{- end }}
          severity: {{ .Values.starboard.values.trivy.severity }}
          nonSslRegistries: {{ toYaml .Values.starboard.values.trivy.nonSslRegistries | nindent 12 }}
        polaris:
          config:
            checks:
              multipleReplicasForDeployment: ignore
              priorityClassNotSet: ignore
              cpuRequestsMissing: warning
              cpuLimitsMissing: warning
              memoryRequestsMissing: warning
              memoryLimitsMissing: warning
              tagNotSpecified: danger
              pullPolicyNotAlways: ignore
              readinessProbeMissing: warning
              livenessProbeMissing: warning
              hostNetworkSet: warning
              hostPortSet: warning
              hostIPCSet: danger
              hostPIDSet: danger
              notReadOnlyRootFilesystem: warning
              privilegeEscalationAllowed: danger
              runAsRootAllowed: warning
              runAsPrivileged: danger
              dangerousCapabilities: danger
              insecureCapabilities: warning
            exemptions:
              - controllerNames:
                - kube-apiserver
                - kube-proxy
                - kube-scheduler
                - etcd-manager-events
                - kube-controller-manager
                - kube-dns
                - etcd-manager-main
                rules:
                - hostPortSet
                - hostNetworkSet
                - readinessProbeMissing
                - livenessProbeMissing
                - cpuRequestsMissing
                - cpuLimitsMissing
                - memoryRequestsMissing
                - memoryLimitsMissing
                - runAsRootAllowed
                - runAsPrivileged
                - notReadOnlyRootFilesystem
                - hostPIDSet
              - controllerNames:
                - kube-flannel-ds
                rules:
                - notReadOnlyRootFilesystem
                - runAsRootAllowed
                - notReadOnlyRootFilesystem
                - readinessProbeMissing
                - livenessProbeMissing
                - cpuLimitsMissing
              - controllerNames:
                - cert-manager
                rules:
                - notReadOnlyRootFilesystem
                - runAsRootAllowed
                - readinessProbeMissing
                - livenessProbeMissing
              - controllerNames:
                - cluster-autoscaler
                rules:
                - notReadOnlyRootFilesystem
                - runAsRootAllowed
                - readinessProbeMissing
              - controllerNames:
                - vpa
                rules:
                - runAsRootAllowed
                - readinessProbeMissing
                - livenessProbeMissing
                - notReadOnlyRootFilesystem
              - controllerNames:
                - datadog
                rules:
                - runAsRootAllowed
                - readinessProbeMissing
                - livenessProbeMissing
                - notReadOnlyRootFilesystem
              - controllerNames:
                - nginx-ingress-controller
                rules:
                - privilegeEscalationAllowed
                - insecureCapabilities
                - runAsRootAllowed
              - controllerNames:
                - dns-controller
                - datadog-datadog
                - kube-flannel-ds
                - kube2iam
                - aws-iam-authenticator
                - datadog
                - kube2iam
                rules:
                - hostNetworkSet
              - controllerNames:
                - aws-iam-authenticator
                - aws-cluster-autoscaler
                - kube-state-metrics
                - dns-controller
                - external-dns
                - dnsmasq
                - autoscaler
                - kubernetes-dashboard
                - install-cni
                - kube2iam
                rules:
                - readinessProbeMissing
                - livenessProbeMissing
              - controllerNames:
                - aws-iam-authenticator
                - nginx-ingress-default-backend
                - aws-cluster-autoscaler
                - kube-state-metrics
                - dns-controller
                - external-dns
                - kubedns
                - dnsmasq
                - autoscaler
                - tiller
                - kube2iam
                rules:
                - runAsRootAllowed
              - controllerNames:
                - aws-iam-authenticator
                - nginx-ingress-controller
                - nginx-ingress-default-backend
                - aws-cluster-autoscaler
                - kube-state-metrics
                - dns-controller
                - external-dns
                - kubedns
                - dnsmasq
                - autoscaler
                - tiller
                - kube2iam
                rules:
                - notReadOnlyRootFilesystem
              - controllerNames:
                - cert-manager
                - dns-controller
                - kubedns
                - dnsmasq
                - autoscaler
                - insights-agent-goldilocks-vpa-install
                - datadog
                rules:
                - cpuRequestsMissing
                - cpuLimitsMissing
                - memoryRequestsMissing
                - memoryLimitsMissing
              - controllerNames:
                - kube2iam
                - kube-flannel-ds
                rules:
                - runAsPrivileged
              - controllerNames:
                - kube-hunter
                rules:
                - hostPIDSet
              - controllerNames:
                - polaris
                - kube-hunter
                - goldilocks
                - insights-agent-goldilocks-vpa-install
                rules:
                - notReadOnlyRootFilesystem
              - controllerNames:
                - insights-agent-goldilocks-controller
                rules:
                - livenessProbeMissing
                - readinessProbeMissing
              - controllerNames:
                - insights-agent-goldilocks-vpa-install
                - kube-hunter
                rules:
                - runAsRootAllowed
{{ end }}