{{- define "vault.enabled" -}}
{{- or .Values.vault.enabled .Values.default.enabled  -}}
{{- end -}}
{{ if eq (include "vault.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy" . }}
  destination:
    namespace: {{ .Values.argocd.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: {{ .Values.vault.chart.name }}
    repoURL: {{ .Values.vault.chart.repo }}
    targetRevision: {{ .Values.vault.chart.version }}
    helm:
      version: v3
      values: |-
        global:
          enabled: true
        injector:
          enabled: true
          replicas: 1
          leaderElector:
            enabled: true
            image:
              repository: "gcr.io/google_containers/leader-elector"
              tag: "0.4"
            ttl: 60s
          image:
            repository: "hashicorp/vault-k8s"
            tag: "0.10.2"
            pullPolicy: Always
          agentImage:
            repository: "vault"
            tag: "1.7.3"
          authPath: "auth/kubernetes"
          failurePolicy: Ignore
          resources: {}
        server:
          image:
            repository: "vault"
            tag: "1.7.3"
            pullPolicy: IfNotPresent
          {{- if and (eq (include "ingress.namespace" .) "traefik-system") .Values.vault.chart.values.ingress.enabled }}
            {{- include "traefik-ingress.helm" (dict "name" .Values.vault.chart.values.ingress.name "traefik" .Values.ingress.traefik.chart.values) | nindent 10 -}}
          {{- end }}
          {{- if and (eq (include "ingress.namespace" .) "ingress-nginx") .Values.vault.chart.values.ingress.enabled }}
            {{- include "traefik-ingress.helm" (dict "name" .Values.vault.chart.values.ingress.name "traefik" .Values.ingress.nginx.chart.values) | nindent 10 -}}
          {{- end }}
          dataStorage:
            enabled: true
            size: {{ .Values.vault.chart.values.pvcSize }}
          auditStorage:
            enabled: false
          dev:
            enabled: false
          {{- if .Values.vault.chart.values.ha -}}
          ha:
            enabled: true
          {{- else }}
          ha:
            enabled: false
          {{- end }}
          serviceAccount:
            create: true
        {{- if and .Values.vault.chart.values.ingress.enabled (or (eq include ("ingress.namespace" .) "traefik-system") (eq include ("ingress.namespace" .) "ingress-nginx")) }}
        ui:
          enabled: true
        {{- end }}
{{ end }}