{{ if eq (include "secrets.isVault" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.argocd.namespace }}
    server: https://kubernetes.default.svc
  project: security
  source:
    path: {{ .Values.vaultSecrets.chart.path }}
    repoURL: {{ .Values.vaultSecrets.chart.repo }}
    targetRevision: {{ .Values.vaultSecrets.chart.targetRevision }}
    plugin:
      - name: argocd-helm-vault-plugin
        env:
          - name: HELM_VALUES
            value: |-
              secrets:
                {{- if eq .Values.monitoring.grafana.values.auth.passwordType "vault" }}
                - secretName: grafana-credentials
                  secretNamespace: {{ .Values.monitoring.namespace }}
                  avpPath: {{ .Values.monitoring.grafana.values.auth.avpPath }}
                  stringData:
                    - key: username
                      placeholder: {{ .Values.monitoring.grafana.values.auth.userKey }}
                    - key: password
                      placeholder: {{ .Values.monitoring.grafana.values.auth.passwordKey }}
                {{- end }}
                {{- if eq .Values.monitoring.values.server.ingress.auth.type "vault" }}
                - secretName: prometheus-basic-auth
                  secretNamespace: {{ .Values.monitoring.namespace }}
                  avpPath: {{ .Values.monitoring.prometheus.values.server.ingress.auth.avpPath }}
                  stringData:
                    - key: auth
                      placeholder: {{ .Values.monitoring.prometheus.values.server.ingress.auth.authKey }}
                {{- end }}
                {{- if eq .Values.minio.values.auth.passwordType "vault" }}
                - secretName: minio-credentials
                  secretNamespace: {{ .Values.minio.namespace }}
                  avpPath: {{ .Values.minio.values.auth.avpPath }}
                  stringData:
                    - key: rootUser
                      placeholder: {{ .Values.minio.values.auth.userKey }}
                    - key: rootPassword
                      placeholder: {{ .Values.minio.values.auth.passwordKey }}
                {{- end }}
{{ end }}