{{- range .Values.subscriptions }}
{{- if ne .installNamespace "olm" }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name }}
  namespace: {{ .installNamespace }}
  {{- if .sameNamespace }}
spec:
  targetNamespaces:
  - {{ .installNamespace }}
  {{- else }}
spec: {}
  {{- end }}
{{- end }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ default "olm" .refNamespace }}
spec:
  channel: stable
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace }}
{{- end }}