{{- range .Values.subscriptions }}
{{- if ne .installNamespace "olm" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .installNamespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .name }}
  namespace: {{ .installNamespace }}
  {{- if .sameNamespace }}
spec:
  targetNamespaces:
    - {{ .installNamespace }}
  {{- else }}
spec: {}
  {{- end }}
{{- end }}
{{- if and .pullSecret .svcAccount }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-pull-secret
  namespace: {{ default "olm" .installNamespace }}
data:
  .dockerconfigjson: {{ .pullSecret }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .svcAccount }}
  namespace: {{ default "olm" .installNamespace }}
imagePullSecrets:
- name: {{ .name }}-pull-secret
{{- end }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ default "olm" .installNamespace }}
spec:
  channel: {{ default "stable" .channel }}
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: {{ .sourceNamespace }}
{{- end }}