{{- define "chaos-engineering.enabled" -}}
{{- .Values.chaosMesh.enabled -}}
{{- end -}}
{{ if eq (include "chaos-engineering.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chaos-engineering
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
{{ end }}