{{- define "chaos-mesh.enabled" -}}
{{- .Values.chaosMesh.enabled  -}}
{{- end -}}
{{ if eq (include "chaos-mesh.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.olm.namespace }}
    server: https://kubernetes.default.svc
  project: chaos-engineering
  source:
    chart: {{ .Values.chaosMesh.chart.name }}
    repoURL: {{ .Values.chaosMesh.chart.repo }}
    targetRevision: {{ .Values.chaosMesh.chart.version }}
    helm:
      version: v3
      values: |-
        
{{ end }}
