{{- define "logging.enabled" -}}
{{- .Values.logging.enabled -}}
{{- end -}}
{{ if eq (include "logging.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: logging
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
{{ end }}