{{- define "loki.enabled" -}}
{{- eq (include "logging.namespace" .) "monitoring" -}}
{{- end -}}
{{ if eq (include "loki.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ (include "logging.namespace" .) }}
    server: https://kubernetes.default.svc
  project: logging
  source:
    chart: {{ .Values.logging.loki.chart.name }}
    repoURL: {{ .Values.logging.loki.chart.repo }}
    targetRevision: {{ .Values.logging.loki.chart.version }}
    helm:
      version: v3
      values: |
        {{- if and (eq (include "ingress.namespace" .) "traefik-system") .Values.logging.loki.values.ingress.enabled }}
        gateway:
          enabled: true
          {{- include "helm-ingress.alternateSpec" (dict "name" .Values.logging.loki.values.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.traefik.values.ingressAnnotations) | nindent 10 -}}
        {{- end }}
        {{- if and (eq (include "ingress.namespace" .) "ingress-nginx") .Values.monitoring.grafana.values.ingress.enabled }}
        gateway:
          enabled: true
          {{- include "helm-ingress.alternateSpec" (dict "name" .Values.logging.loki.values.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.nginx.values.ingressAnnotations) | nindent 10 -}}
        {{- end }}
        test:
          enabled: false
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: false
          lokiCanary:
            enabled: false
        write:
          replicas: 1
          minReplicas: 0
          {{- if .Values.default.storageClass }}
          persistence:
            enabled: true
            storageClassName: {{ .Values.default.storageClass }}
            size: {{ .Values.logging.loki.values.persistence.write }}
          {{- else }}
          persistence:
            enabled: false
          {{- end }}
        read:
          replicas: 1
          minReplicas: 0
          {{- if .Values.default.storageClass }}
          persistence:
            enabled: true
            storageClassName: {{ .Values.default.storageClass }}
            size: {{ .Values.logging.loki.values.persistence.write }}
          {{- else }}
          persistence:
            enabled: false
        {{- end }}
        loki:
          auth_enabled: false
          limits_config:
            enforce_metric_name: false
            reject_old_samples: true
            reject_old_samples_max_age: 336h
            retention_period: {{ .Values.logging.loki.values.retention }}
          server:
            http_listen_port: 3100
          podSecurityContext:
            fsGroup: 0
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
{{ end }}