{{- define "promtail.enabled" -}}
{{- and .Values.logging.promtail.enabled (eq (include "logging.namespace" .) "monitoring") -}}
{{- end -}}
{{ if eq (include "promtail.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ (include "logging.namespace" .) }}
    server: https://kubernetes.default.svc
  project: logging
  source:
    chart: {{ .Values.logging.promtail.chart.name }}
    repoURL: {{ .Values.logging.promtail.chart.repo }}
    targetRevision: {{ .Values.logging.promtail.chart.version }}
    helm: |
      {{- if .Values.logging.promtail.values.installOnControllPlane }}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      {{- end }}
      defaultVolumes:
        - name: containers
          hostPath:
            path: {{ .Values.logging.promtail.values.runtimeLogs }}
        - name: pods
          hostPath:
            path: /var/log/pods
      defaultVolumeMounts:
        - name: containers
          path: {{ .Values.logging.promtail.values.runtimeLogs }}
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
      {{- if .Values.logging.promtail.values.extraVolumes }}
      extraVolumes:
        {{- toYaml .Values.logging.promtail.values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- if .Values.logging.promtail.values.extraVolumeMounts }}
      extraVolumeMounts:
        {{- toYaml .Values.logging.promtail.values.extraVolumeMounts | nindent 8 }}
      {{- end }}
      {{- if .Values.logging.promtail.values.extraContainers }}
      config:
        logLevel: info
        serverPort: 3101
        lokiAddress: http://loki:3100.monitoring/loki/api/v1/push
        extraScrapeConfigs: |-
          {{- if .Values.logging.promtail.values.extraScrapeConfigs -}}
            {{- with .Values.logging.promtail.values.extraScrapeConfigs }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}
        extraRelabelConfigs:
          {{- with .Values.logging.promtail.values.extraRelabelConfigs }}
              {{- toYaml . | nindent 10 }}
          {{- end }}
{{ end }}