{{- define "discord.enabled" -}}
{{- and .Values.monitoring.discord.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.values.alertmanager.enabled -}}
{{- end -}}
{{ if eq (include "discord.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.monitoring.namespace }}
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: {{ .Values.monitoring.discord.chart.name }}
    repoURL: {{ .Values.monitoring.discord.chart.repo }}
    targetRevision: {{ .Values.monitoring.discord.chart.version }}
    helm:
      version: v3
      values: |-
        config:
          {{- if .Values.monitoring.prometheus.values.server.ingress.enabled }}
          prometheusURL: {{ include "url-constructor" (dict "name" .Values.monitoring.prometheus.values.server.ingress.name "ingress" .Values.ingress.ingressDefinition) }}
          {{- end }}
          messageType: severity
          firingCountToMention: 20
          {{- if .Values.monitoring.discord.values.rolesToMention }}
          rolesToMention:
            {{- range .Values.monitoring.discord.values.rolesToMention }}
              - {{ . }}
            {{- end }}
          {{- end }}
          status:
            firing:
              emoji: ":x:"
              color: 10038562
            resolved:
              emoji: ":white_check_mark:"
              color: 3066993
          severity:
            label: severity
            values:
              unknown:
                color: 9807270
                emoji: ":grey_question:"
              information:
                color: 3447003
                emoji: ":information_source:"
              warning:
                color: 15844367
                emoji: ":warning:"
                priority: 1
              critical:
                color: 11027200
                emoji: ":x:"
                priority: 2
              disaster:
                color: 10038562
                emoji: ":fire:"
                priority: 3
          severitiesToMention:
            - disaster
            - critical
            severitiesToIgnoreWhenAlone:
              - information
          {{- if .Values.monitoring.discord.values.channels }}  
          channels:
            {{- toYaml .Values.monitoring.discord.values.channels | nindent 12 }}
          {{- else }}
          channels: {}
          {{- end }}
{{ end }}
