{{- define "fio.enabled" -}}
{{- and .Values.monitoring.fio.enabled .Values.monitoring.enabled .Values.monitoring.prometheus.enabled -}}
{{- end -}}
{{ if eq (include "fio.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fio-exporter
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy" . }}
  destination:
    namespace: {{ .Values.olm.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .Values.monitoring.fio.chart.path }}
    repoURL: {{ .Values.monitoring.fio.chart.repo }}
    targetRevision: {{ .Values.monitoring.fio.chart.targetRevision }}
    helm:
      version: v3
      values: |-
        {{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
        prometheusScrape:
          enabled: true
        {{- end }}
{{ end }}
