{{- define "grafana.enabled" -}}
{{- .Values.monitoring.grafana.enabled -}}
{{- end -}}
{{ if eq (include "grafana.enabled" .) "true" }}
{{- if eq .Values.monitoring.grafana.values.auth.passwordType "raw" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: grafana-credentials
  namespace: {{ .Values.monitoring.namespace }}
type: Opaque
data:
  username: {{ .Values.monitoring.grafana.values.auth.adminUser | b64enc }}
  password: {{ .Values.monitoring.grafana.values.auth.adminPassword | b64enc }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.monitoring.namespace }}
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: {{ .Values.monitoring.grafana.chart.name }}
    repoURL: {{ .Values.monitoring.grafana.chart.repo }}
    targetRevision: {{ .Values.monitoring.grafana.chart.version }}
    helm:
      version: v3
      values: |-
        {{- if .Values.monitoring.grafana.values.server.rootUrl }}
        server:
          root_url: {{ .Values.monitoring.grafana.values.server.rootUrl }}
        {{- end }}
        admin:
          existingSecret: "grafana-credentials"
          userKey: username
          passwordKey: password
        {{- if .Values.monitoring.prometheus.enabled }}
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring
                access: proxy
              {{- if eq (include "logging.namespace" .) "monitoring" }}
              - name: Loki
                type: loki
                url: http://loki.monitoring:3100
                access: proxy
              {{- end }}
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            node-monitor-detailled:
              gnetId: 1860
              revision: 27
              datasource: Prometheus
            kube-monitor:
              gnetId: 11000
              revision: 2
              datasource: Prometheus
            kube-resources:
              gnetId: 11671
              revision: 1
              datasource: Prometheus
            kube-pvc:
              gnetId: 13646
              revision: 2
              datasource: Prometheus
            {{- if and .Values.monitoring.goldpinger.enabled .Values.monitoring.goldpinger.values.enableGrafanaDashboard }}
            goldpinger:
              gnetId: 10949
              revision: 1
              datasource: Prometheus
            {{- end }}
            {{- if and .Values.ingress.nginx.values.monitor .Values.ingress.nginx.values.enableGrafanaDashboard (eq (include "ingress.namespace" .) "ingress-nginx") }}
            nginx:
              gnetId: 9614
              revision: 1
              datasource: Prometheus
            {{- end }}
            {{- if and .Values.ingress.traefik.values.monitor .Values.ingress.traefik.values.enableGrafanaDashboard (eq (include "ingress.namespace" .) "traefik-system") }}
            traefik:
              gnetId: 11462
              revision: 1
              datasource: Prometheus
            {{- end }}
            {{- if and .Values.monitoring.fio.enabled .Values.monitoring.fio.values.enableGrafanaDashboard }}
            fio:
              gnetId: 16284
              revision: 3
              datasource: Prometheus
            {{- end }}
            {{- if and .Values.monitoring.helmExporter.enabled .Values.monitoring.helmExporter.values.enableGrafanaDashboard }}
            helm-exporter:
              gnetId: 9367
              revision: 2
              datasource: Prometheus
            {{- end }}
            {{- if and .Values.monitoring.blackboxExporter.enabled .Values.monitoring.blackboxExporter.values.enableGrafanaDashboard }}
            blackbox-exporter:
              gnetId: 13659
              revision: 1
              datasource: Prometheus
            {{- end }}
            {{- if .Values.monitoring.grafana.values.customDashboardsGNET }}
              {{- with .Values.monitoring.grafana.values.customDashboardsGNET }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
            {{- if .Values.monitoring.grafana.values.customDashboards }}
              {{- with .Values.monitoring.grafana.values.customDashboards }}
                {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
            {{- if eq (include "logging.namespace" .) "monitoring" }}
            loki:
              json: |-
                {
                  "annotations": {
                    "list": [
                      {
                        "builtIn": 1,
                        "datasource": "-- Grafana --",
                        "enable": true,
                        "hide": true,
                        "iconColor": "rgba(0, 211, 255, 1)",
                        "name": "Annotations & Alerts",
                        "type": "dashboard"
                      }
                    ]
                  },
                  "description": "Loki logs panel with prometheus variables",
                  "editable": true,
                  "gnetId": 12019,
                  "graphTooltip": 0,
                  "id": 13,
                  "iteration": 1618849463581,
                  "links": [],
                  "panels": [
                    {
                      "aliasColors": {},
                      "bars": true,
                      "dashLength": 10,
                      "dashes": false,
                      "datasource": "Loki",
                      "fieldConfig": {
                        "defaults": {
                          "custom": {}
                        },
                        "overrides": []
                      },
                      "fill": 1,
                      "fillGradient": 0,
                      "gridPos": {
                        "h": 3,
                        "w": 24,
                        "x": 0,
                        "y": 0
                      },
                      "hiddenSeries": false,
                      "id": 6,
                      "legend": {
                        "avg": false,
                        "current": false,
                        "max": false,
                        "min": false,
                        "show": false,
                        "total": false,
                        "values": false
                      },
                      "lines": false,
                      "linewidth": 1,
                      "nullPointMode": "null",
                      "options": {
                        "dataLinks": []
                      },
                      "percentage": false,
                      "pointradius": 2,
                      "points": false,
                      "renderer": "flot",
                      "seriesOverrides": [],
                      "spaceLength": 10,
                      "stack": false,
                      "steppedLine": false,
                      "targets": [
                        {
                          "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"[$__interval]))",
                          "refId": "A"
                        }
                      ],
                      "thresholds": [],
                      "timeFrom": null,
                      "timeRegions": [],
                      "timeShift": null,
                      "title": "",
                      "tooltip": {
                        "shared": true,
                        "sort": 0,
                        "value_type": "individual"
                      },
                      "type": "graph",
                      "xaxis": {
                        "buckets": null,
                        "mode": "time",
                        "name": null,
                        "show": true,
                        "values": []
                      },
                      "yaxes": [
                        {
                          "format": "short",
                          "label": null,
                          "logBase": 1,
                          "max": null,
                          "min": null,
                          "show": false
                        },
                        {
                          "format": "short",
                          "label": null,
                          "logBase": 1,
                          "max": null,
                          "min": null,
                          "show": false
                        }
                      ],
                      "yaxis": {
                        "align": false,
                        "alignLevel": null
                      }
                    },
                    {
                      "datasource": "Loki",
                      "fieldConfig": {
                        "defaults": {
                          "custom": {}
                        },
                        "overrides": []
                      },
                      "gridPos": {
                        "h": 25,
                        "w": 24,
                        "x": 0,
                        "y": 3
                      },
                      "id": 2,
                      "maxDataPoints": "",
                      "options": {
                        "showLabels": false,
                        "showTime": true,
                        "sortOrder": "Descending",
                        "wrapLogMessage": true
                      },
                      "targets": [
                        {
                          "expr": "{namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"",
                          "refId": "A"
                        }
                      ],
                      "timeFrom": null,
                      "timeShift": null,
                      "title": "Logs Panel",
                      "type": "logs"
                    },
                    {
                      "content": "<div style=\"text-align:center\"> For Grafana Loki blog example </div>\n\n\n",
                      "datasource": null,
                      "fieldConfig": {
                        "defaults": {
                          "custom": {}
                        },
                        "overrides": []
                      },
                      "gridPos": {
                        "h": 3,
                        "w": 24,
                        "x": 0,
                        "y": 28
                      },
                      "id": 4,
                      "mode": "html",
                      "timeFrom": null,
                      "timeShift": null,
                      "title": "",
                      "transparent": true,
                      "type": "text"
                    }
                  ],
                  "schemaVersion": 25,
                  "style": "dark",
                  "tags": [],
                  "templating": {
                    "list": [
                      {
                        "allValue": null,
                        "current": {
                          "selected": false,
                          "text": "kube-system",
                          "value": "kube-system"
                        },
                        "datasource": "Prometheus",
                        "definition": "label_values(kube_pod_info, namespace)",
                        "hide": 0,
                        "includeAll": false,
                        "label": null,
                        "multi": false,
                        "name": "namespace",
                        "options": [],
                        "query": "label_values(kube_pod_info, namespace)",
                        "refresh": 1,
                        "regex": "",
                        "skipUrlSync": false,
                        "sort": 0,
                        "tagValuesQuery": "",
                        "tags": [],
                        "tagsQuery": "",
                        "type": "query",
                        "useTags": false
                      },
                      {
                        "allValue": ".*",
                        "current": {
                          "selected": false,
                          "text": "All",
                          "value": "$__all"
                        },
                        "datasource": "Prometheus",
                        "definition": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)",
                        "hide": 0,
                        "includeAll": true,
                        "label": null,
                        "multi": true,
                        "name": "pod",
                        "options": [],
                        "query": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)",
                        "refresh": 1,
                        "regex": "",
                        "skipUrlSync": false,
                        "sort": 0,
                        "tagValuesQuery": "",
                        "tags": [],
                        "tagsQuery": "",
                        "type": "query",
                        "useTags": false
                      },
                      {
                        "current": {
                          "selected": false,
                          "text": "level=warn",
                          "value": "level=warn"
                        },
                        "hide": 0,
                        "label": null,
                        "name": "search",
                        "options": [
                          {
                            "selected": true,
                            "text": "level=warn",
                            "value": "level=warn"
                          }
                        ],
                        "query": "level=warn",
                        "skipUrlSync": false,
                        "type": "textbox"
                      }
                    ]
                  },
                  "time": {
                    "from": "now-30m",
                    "to": "now"
                  },
                  "timepicker": {
                    "refresh_intervals": [
                      "10s",
                      "30s",
                      "1m",
                      "5m",
                      "15m",
                      "30m",
                      "1h",
                      "2h",
                      "1d"
                    ]
                  },
                  "timezone": "browser",
                  "title": "Loki Dashboard quick search",
                  "uid": "liz0yRxZ0",
                  "version": 1
                }
            {{- end }}
        {{- end }}
        {{- if and (eq (include "ingress.namespace" .) "traefik-system") .Values.monitoring.grafana.values.ingress.enabled }}
          {{- include "helm-ingress.defaultSpec" (dict "name" .Values.monitoring.grafana.values.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.traefik.values.ingressAnnotations) | nindent 8 -}}
        {{- end }}
        {{- if and (eq (include "ingress.namespace" .) "ingress-nginx") .Values.monitoring.grafana.values.ingress.enabled }}
          {{- include "helm-ingress.defaultSpec" (dict "name" .Values.monitoring.grafana.values.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.nginx.values.ingressAnnotations) | nindent 8 -}}
        {{- end }}
        {{- if .Values.default.storageClass }}
        persistence:
          enabled: true
          storageClass: {{ .Values.default.storageClass }}
          size: {{ quote .Values.monitoring.grafana.values.pvcSize }}
          accessModes:
            - {{ (include "accessModes.template" .) }}
          {{- else }}
        persistence:
          enabled: false
        {{- end }}
        {{- if .Values.proxies.enabled }}
        env:
          http_proxy: {{ .Values.proxies.value }}
          https_proxy: {{ .Values.proxies.value }}
          no_proxy: {{ .Values.proxies.noProxy }}
        {{- end }}
{{ end }}
