{{- define "prometheus-msteams.enabled" -}}
{{- and .Values.monitoring.prometheusMsTeams.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.values.alertmanager.enabled -}}
{{- end -}}
{{ if eq (include "prometheus-msteams.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-msteams
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.monitoring.namespace }}
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: {{ .Values.monitoring.prometheusMsTeams.chart.name }}
    repoURL: {{ .Values.monitoring.prometheusMsTeams.chart.repo }}
    targetRevision: {{ .Values.monitoring.prometheusMsTeams.chart.version }}
    helm:
      version: v3
      values: |-
        {{- if .Values.proxies.enabled }}
        extraEnvs:
          HTTP_PROXY: {{ .Values.proxies.value }}
          HTTPS_PROXY: {{ .Values.proxies.value }}
        {{- end }}
        {{- if .Values.monitoring.prometheusMsTeams.values.monitor }}
        metrics:
          serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
          scrapeInterval: 30s
        {{- else }}
        metrics:
          enabled: false
        {{- end }}
        {{- if .Values.monitoring.prometheusMsTeams.values.hooks }}
        connectors:
        {{- range $index, $map := .Values.monitoring.prometheusMsTeams.values.hooks }}
          {{- range $k, $v := $map }}
          - {{ $k }}: {{ $v }}
          {{- end }}
        {{- end }}
        {{- end }}
{{ end }}
