{{- range .Values.vaultSecrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .secretName }}
  namespace: {{ .secretNamespace }}
  annotations:
    avp.kubernetes.io/path: {{ .avpPath }}
type: Opaque
stringData:
  {{- range $k, $v := .stringData }}
  {{ $v.key }}: {{ printf "<%v>" $v.placeholder }}
  {{- end }}
{{- end }}
