{{- define "storage.enabled" -}}
{{- .Values.minio.enabled -}}
{{- end -}}
{{ if eq (include "storage.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  {{- if .Values.minio.enabled }}
  - namespace: '{{ .Values.minio.namespace }}'
    server: '*'
  {{- end }}
  sourceRepos:
  - '*'
{{ end }}