{{- define "argoEvents.enabled" -}}
{{- or .Values.argoEvents.enabled .Values.default.enabled -}}
{{- end -}}
{{ if eq (include "argoEvents.enabled" .) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoEvents
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.argoEvents.namespace }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    chart: {{ .Values.argoEvents.chart.name }}
    repoURL: {{ .Values.argoEvents.chart.repo }}
    targetRevision: {{ .Values.argoEvents.chart.version }}
    helm:
      version: v3
      values: |-
{{ end }}
