{{- define "argocd.enabled" -}}
{{- or .Values.argocd.enabled .Values.default.enabled -}}
{{- end -}}
{{ if eq (include "argocd.enabled" .) "true" }}
{{- if .Values.argocd.chart.values.avp.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: avp
  namespace: argocd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avp-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  avp-config.yaml: |
    AVP_K8S_ROLE: {{ .Values.argocd.chart.values.avp.saName }}
    AVP_TYPE: vault
    {{- if .Values.vault.enabled }}
    VAULT_ADDR: 'http://vault.{{ .Values.vault.namespace }}:8200'
    {{- else }}
    VAULT_ADDR: {{ .Values.argocd.chart.values.avp.auth.vaultUrl }}
    {{- end }}
    AVP_AUTH_TYPE: {{ .Values.argocd.chart.values.avp.auth.type }}
    AVP_K8S_MOUNT_PATH: {{ .Values.argocd.chart.values.avp.auth.path }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoception
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.argocd.namespace }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    chart: {{ .Values.argocd.chart.name }}
    repoURL: {{ .Values.argocd.chart.repo }}
    targetRevision: {{ .Values.argocd.chart.version }}
    helm:
      version: v3
      values: |-
        controller:
          enableStatefulSet: true
        applicationset:
          enabled: false
        {{- if .Values.argocd.chart.values.ha }}
        redis-ha:
          enabled: true
          securityContext: {}
          haproxy:
            securityContext: {}
        {{- end }}
        configs:
          createSecret: false
        {{- if and .Values.argocd.chart.values.monitor .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
        metrics:
          enabled: false
          service:
            annotations:
              prometheus.io/scrape: 'true'
              prometheus.io/port: '8085'
              prometheus.io/path: '/metrics'
            servicePort: 8085
        {{- end }}
        server:
          {{- if .Values.argocd.chart.values.ha }}
          replicas: 2
          {{- end }}
          {{- if and (eq (include "ingress.namespace" .) "traefik-system") .Values.argocd.chart.values.ingress.enabled }}
            {{- include "helm-ingress.definition" (dict "name" .Values.argocd.chart.values.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.traefik.chart.values.ingressAnnotations) | nindent 10 }}
          {{- end }}
          {{- if and (eq (include "ingress.namespace" .) "ingress-nginx") .Values.argocd.chart.values.ingress.enabled }}
            {{- include "helm-ingress.definition" (dict "name" .Values.argocd.chart.values.ingress.name "ingressDefinition" .Values.ingress.ingressDefinition "annotations" .Values.ingress.nginx.chart.values.ingressAnnotations) | nindent 10 }}
          {{- end }}
          logLevel: {{ .Values.argocd.chart.values.logLevel }}
          {{- if or .Values.argocd.chart.values.ha .Values.proxies.enabled }}
          env:
            {{- if .Values.argocd.chart.values.ha }}
            - name: ARGOCD_API_SERVER_REPLICAS
              value: '2'
            {{- end }}
            {{- if .Values.proxies.enabled }}
            - name: http_proxy
              value: {{ quote .Values.proxies.value }}
            - name: https_proxy
              value: {{ quote .Values.proxies.value }}
            - name: no_proxy
              value: argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,argocd-dex-server,{{ .Values.proxies.noProxy }}
            {{- end }}
          {{- end }}
          config:
            {{- if .Values.argocd.chart.values.ingress.enabled }}
            url: {{ include "url-constructor" (dict "name" .Values.argocd.chart.values.ingress.name "ingress" .Values.ingress.ingressDefinition) }}
            {{- end }}
            application.instanceLabelKey: argocd.argoproj.io/instance
            {{- if .Values.argocd.chart.values.avp.enabled }}
            configManagementPlugins: |-
              - name: argocd-vault-plugin
                generate:
                  command: ["argocd-vault-plugin"]
                  args: ["generate", "./ -c /etc/avp-config.yaml"]
            {{- end }}
            repositories: |
              - url: https://github.com/panzouh/argo-repository.git
              {{- if .Values.argocd.chart.values.repositories }}
                {{- toYaml .Values.argocd.chart.values.repositories | nindent 14 }}
              {{- end }}
        repoServer:
          {{- if .Values.argocd.chart.values.ha }}
          replicas: 2
          {{- end }}
          {{- if .Values.argocd.chart.values.avp.enabled }}
          serviceAccount:
            create: false
            name: avp
            automountServiceAccountToken: true
          volumeMounts:
            - mountPath: /usr/local/bin/argocd-vault-plugin
              name: custom-tools
              subPath: argocd-vault-plugin
            - mountPath: /etc/avp-config.yaml
              name: avp-config
              subPath: avp-config.yaml
          volumes:
            - name: custom-tools
              emptyDir: {}
            - name: avp-config
              configMap:
                name: avp-cm
          initContainers:
          - name: download-tools
            image: cirrusci/wget:latest
            command: [sh, -c]
            env:
              - name: AVP_VERSION
                value: {{ quote .Values.argocd.chart.values.avp.version }}
              {{- if .Values.proxies.enabled }}
              - name: http_proxy
                value: {{ quote .Values.proxies.value }}
              - name: https_proxy
                value: {{ quote .Values.proxies.value }}
              {{- end }}
            args:
              - wget -O /custom-tools/argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 && chmod 0755 /custom-tools/argocd-vault-plugin
            volumeMounts:
              - mountPath: /custom-tools
                name: custom-tools
          env:
            - name: ARGOCD_EXEC_TIMEOUT
              value: "300s"
            {{- if .Values.proxies.enabled }}
            - name: http_proxy
              value: {{ quote .Values.proxies.value }}
            - name: https_proxy
              value: {{ quote .Values.proxies.value }}
            - name: no_proxy
              value: argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,argocd-dex-server,{{ .Values.proxies.noProxy }}
            {{- end }}
          {{- end }}
{{ end }}
