{{- define "gitlab-runners.enabled" -}}
{{- gt (len .Values.gitlabRunners.values.runners) 0 -}}
{{- end -}}
{{- $argoFinalizers := (include "argocd.applications.finalizers" .) -}}
{{- $argoSyncPolicy := (include "cluster.syncPolicy.default" .) -}}
{{- $argocdNamespace := .Values.argocd.namespace -}}
{{- $gitlabChart := .Values.gitlabRunners.chart -}}
{{ if eq (include "gitlab-runners.enabled" .) "true" }}
{{- range .Values.gitlabRunners.values.runners }}
{{- if gt (len (default 0 .pullSecrets)) 0 }}
{{- $runnerName := .runnerName -}}
{{- $runnerNamespace := default "gitlab" .runnerNamespace -}}
{{- range $k,$v := .pullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $runnerName }}-{{ $k }}-regcred
  namespace: {{ $runnerNamespace }}
data:
  .dockerconfigjson: {{ $v }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .runnerName }}
  namespace: {{ $argocdNamespace }}
  finalizers:
  {{- $argoFinalizers | nindent 4 }}
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ default "gitlab" .runnerNamespace }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    chart: {{ $gitlabChart.name }}
    repoURL: {{ $gitlabChart.repo }}
    targetRevision: {{ $gitlabChart.version }}
    helm:
      version: v3
      values: |-
        replicas: {{ default 1 .replicas }}
        imagePullPolicy: {{ default "IfNotPresent" .imagePullPolicy }}
        terminationGracePeriodSeconds: 3600
        gitlabUrl: {{ .gitlabUrl }}
        runnerRegistrationToken: {{ .runnerToken }}
        concurrent: 10
        checkInterval: 30
        rbac:
          create: true
          {{- if .isPrivileged }}
          clusterWideAccess: true
          {{- else }}
          clusterWideAccess: false
          {{- end }}
          podSecurityPolicy:
            enabled: false
            resourceNames:
              - gitlab-runner
        runners:
          disable_cache: false
          tags: {{ .runnerTags }}
          {{- if gt (len ( default 0 .pullSecrets)) 0 }}
          {{- $runnerName := .runnerName }}
          imagePullSecrets:
            {{- range $k, $v := .pullSecrets }}
            - {{ $runnerName }}-{{ $k }}-regcred
            {{- end }}
          {{- end }}
          cache_dir: "/cache"
          config: |-
            [[runners]]
              executor = "docker"
              [runners.docker]
                tls_verify = false
                image = "docker:{{ default "19.03.12" .dockerVersion }}"
                {{- if .isPrivileged }}
                privileged = true
                {{- end }}
                disable_cache = false
                volumes = ["/cache"]
          runUntagged: false
          protected: false
          {{- if .isPrivileged }}
          privileged: true
          {{- end }}
          cache: {}
          builds:
            cpuRequests: 100m
            memoryRequests: 128Mi
          services:
            cpuRequests: 100m
            memoryRequests: 128Mi
          helpers:
            cpuRequests: 100m
            memoryRequests: 128Mi
        securityContext:
          fsGroup: 65533
          runAsUser: 100
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
{{- end }}
{{ end }}