{{- define "kubernetes-replicator.enabled" -}}
{{- .Values.kubernetesReplicator.enabled -}}
{{- end -}}
{{ if eq (include "kubernetes-replicator.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-replicator
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.kubernetesReplicator.namespace }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    chart: {{ .Values.kubernetesReplicator.chart.name }}
    repoURL: {{ .Values.kubernetesReplicator.chart.repo }}
    targetRevision: {{ .Values.kubernetesReplicator.chart.version }}
    helm:
      version: v3
      values: |-
        grantClusterAdmin: {{ .Values.kubernetesReplicator.values.grantClusterAdmin }}
{{ end }}