{{- define "namespace-configuration-operator.enabled" -}}
{{- and .Values.namespaceConfiguratorOperator.enabled .Values.certmanager.enabled  -}}
{{- end -}}
{{ if eq (include "namespace-configuration-operator.enabled" .) "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-configuration-operator
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  {{- include "argocd.applications.finalizers" . | nindent 4 }}
spec:
  {{- template "cluster.syncPolicy.default" . }}
  destination:
    namespace: {{ .Values.namespaceConfiguratorOperator.namespace }}
    server: https://kubernetes.default.svc
  project: integration
  source:
    chart: {{ .Values.namespaceConfiguratorOperator.chart.name }}
    repoURL: {{ .Values.namespaceConfiguratorOperator.chart.repo }}
    targetRevision: {{ .Values.namespaceConfiguratorOperator.chart.version }}
    helm:
      version: v3
      values: |-
        {{- if and .Values.namespaceConfiguratorOperator.values.monitor .Values.monitoring.prometheus.enabled }}
        enableMonitoring: true
        {{- else }}
        enableMonitoring: false
        {{- end }}
        enableCertManager: true
{{ end }}
